# Generated by Django 3.0.7 on 2020-06-07 05:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='untilWhen',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 7, 14, 54, 32, 781826)),
        ),
    ]
